# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/benjamin/PynqNet/PynqNetTop/PynqNetTop.srcs/sources_1/bd/PynqNetTop/ip/PynqNetTop_axi_gpio_0_0/PynqNetTop_axi_gpio_0_0.xci
# IP: The module: 'PynqNetTop_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/benjamin/PynqNet/PynqNetTop/PynqNetTop.srcs/sources_1/bd/PynqNetTop/ip/PynqNetTop_axi_gpio_0_0/PynqNetTop_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PynqNetTop_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/benjamin/PynqNet/PynqNetTop/PynqNetTop.srcs/sources_1/bd/PynqNetTop/ip/PynqNetTop_axi_gpio_0_0/PynqNetTop_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PynqNetTop_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/benjamin/PynqNet/PynqNetTop/PynqNetTop.srcs/sources_1/bd/PynqNetTop/ip/PynqNetTop_axi_gpio_0_0/PynqNetTop_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PynqNetTop_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/benjamin/PynqNet/PynqNetTop/PynqNetTop.srcs/sources_1/bd/PynqNetTop/ip/PynqNetTop_axi_gpio_0_0/PynqNetTop_axi_gpio_0_0.xci
# IP: The module: 'PynqNetTop_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/benjamin/PynqNet/PynqNetTop/PynqNetTop.srcs/sources_1/bd/PynqNetTop/ip/PynqNetTop_axi_gpio_0_0/PynqNetTop_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PynqNetTop_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/benjamin/PynqNet/PynqNetTop/PynqNetTop.srcs/sources_1/bd/PynqNetTop/ip/PynqNetTop_axi_gpio_0_0/PynqNetTop_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PynqNetTop_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/benjamin/PynqNet/PynqNetTop/PynqNetTop.srcs/sources_1/bd/PynqNetTop/ip/PynqNetTop_axi_gpio_0_0/PynqNetTop_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PynqNetTop_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
