#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Dec 02 16:48:17 CET 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto d12cc4fe205646538daf1b5100dfc90e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot crc_TB_behav xil_defaultlib.crc_TB -log elaborate.log"
xelab -wto d12cc4fe205646538daf1b5100dfc90e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot crc_TB_behav xil_defaultlib.crc_TB -log elaborate.log

