#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu May 07 10:27:00 CEST 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 4226c0e2577e4090896c2d41180c5140 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot PmodCLK_tb_behav xil_defaultlib.PmodCLK_tb -log elaborate.log"
xelab -wto 4226c0e2577e4090896c2d41180c5140 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot PmodCLK_tb_behav xil_defaultlib.PmodCLK_tb -log elaborate.log

