# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/benjamin/Repositories/PynqNet/Hardware/Pynq_Echo_Server/Pynq_Echo_Server.srcs/sources_1/bd/Echo_Server/ip/Echo_Server_axi_gpio_1_0/Echo_Server_axi_gpio_1_0.xci
# IP: The module: 'Echo_Server_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/benjamin/Repositories/PynqNet/Hardware/Pynq_Echo_Server/Pynq_Echo_Server.srcs/sources_1/bd/Echo_Server/ip/Echo_Server_axi_gpio_1_0/Echo_Server_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Echo_Server_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/benjamin/Repositories/PynqNet/Hardware/Pynq_Echo_Server/Pynq_Echo_Server.srcs/sources_1/bd/Echo_Server/ip/Echo_Server_axi_gpio_1_0/Echo_Server_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Echo_Server_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/benjamin/Repositories/PynqNet/Hardware/Pynq_Echo_Server/Pynq_Echo_Server.srcs/sources_1/bd/Echo_Server/ip/Echo_Server_axi_gpio_1_0/Echo_Server_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Echo_Server_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/benjamin/Repositories/PynqNet/Hardware/Pynq_Echo_Server/Pynq_Echo_Server.srcs/sources_1/bd/Echo_Server/ip/Echo_Server_axi_gpio_1_0/Echo_Server_axi_gpio_1_0.xci
# IP: The module: 'Echo_Server_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/benjamin/Repositories/PynqNet/Hardware/Pynq_Echo_Server/Pynq_Echo_Server.srcs/sources_1/bd/Echo_Server/ip/Echo_Server_axi_gpio_1_0/Echo_Server_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Echo_Server_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/benjamin/Repositories/PynqNet/Hardware/Pynq_Echo_Server/Pynq_Echo_Server.srcs/sources_1/bd/Echo_Server/ip/Echo_Server_axi_gpio_1_0/Echo_Server_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Echo_Server_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/benjamin/Repositories/PynqNet/Hardware/Pynq_Echo_Server/Pynq_Echo_Server.srcs/sources_1/bd/Echo_Server/ip/Echo_Server_axi_gpio_1_0/Echo_Server_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Echo_Server_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
