# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ZyboEthernet/ZyboEthernet.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZyboEthernet || ORIG_REF_NAME==ZyboEthernet} -quiet] -quiet

# IP: bd/ZyboEthernet/ip/ZyboEthernet_processing_system7_0_0/ZyboEthernet_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZyboEthernet_processing_system7_0_0 || ORIG_REF_NAME==ZyboEthernet_processing_system7_0_0} -quiet] -quiet

# XDC: bd/ZyboEthernet/ZyboEthernet_ooc.xdc
