# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Pynq_constraint_file.xdc

# Block Designs: bd/Echo_Server/Echo_Server.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Echo_Server || ORIG_REF_NAME==Echo_Server} -quiet] -quiet

# IP: bd/Echo_Server/ip/Echo_Server_processing_system7_0_0/Echo_Server_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Echo_Server_processing_system7_0_0 || ORIG_REF_NAME==Echo_Server_processing_system7_0_0} -quiet] -quiet

# IP: bd/Echo_Server/ip/Echo_Server_axi_gpio_0_0/Echo_Server_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Echo_Server_axi_gpio_0_0 || ORIG_REF_NAME==Echo_Server_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Echo_Server/ip/Echo_Server_ps7_0_axi_periph_0/Echo_Server_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Echo_Server_ps7_0_axi_periph_0 || ORIG_REF_NAME==Echo_Server_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Echo_Server/ip/Echo_Server_rst_ps7_0_100M_0/Echo_Server_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Echo_Server_rst_ps7_0_100M_0 || ORIG_REF_NAME==Echo_Server_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Echo_Server/ip/Echo_Server_xbar_0/Echo_Server_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Echo_Server_xbar_0 || ORIG_REF_NAME==Echo_Server_xbar_0} -quiet] -quiet

# IP: bd/Echo_Server/ip/Echo_Server_SixDigitHexDisplay_0_0/Echo_Server_SixDigitHexDisplay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Echo_Server_SixDigitHexDisplay_0_0 || ORIG_REF_NAME==Echo_Server_SixDigitHexDisplay_0_0} -quiet] -quiet

# IP: bd/Echo_Server/ip/Echo_Server_ManInput_0_0/Echo_Server_ManInput_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Echo_Server_ManInput_0_0 || ORIG_REF_NAME==Echo_Server_ManInput_0_0} -quiet] -quiet

# IP: bd/Echo_Server/ip/Echo_Server_auto_pc_0/Echo_Server_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Echo_Server_auto_pc_0 || ORIG_REF_NAME==Echo_Server_auto_pc_0} -quiet] -quiet

# XDC: bd/Echo_Server/Echo_Server_ooc.xdc
