# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-2260-Laptop/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.cache/wt [current_project]
set_property parent.project_path /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part www.digilentinc.com:pynq-z1:part0:1.0 [current_project]
set_property ip_output_repo /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/axis/rtl/arbiter.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/arp.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/arp_cache.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/arp_eth_rx.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/arp_eth_tx.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/axis/rtl/axis_adapter.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/axis/rtl/axis_async_fifo.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/axis/rtl/axis_async_fifo_adapter.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/axis/rtl/axis_fifo.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/axis_gmii_rx.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/axis_gmii_tx.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/eth_arb_mux.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/eth_axis_rx.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/eth_axis_tx.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/eth_mac_1g.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/eth_mac_1g_gmii.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/eth_mac_1g_gmii_fifo.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/gmii_phy_if.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/ip.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/ip_arb_mux.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/ip_complete.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/ip_eth_rx.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/ip_eth_tx.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/lfsr.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/oddr.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/axis/rtl/priority_encoder.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/ssio_sdr_in.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/ssio_sdr_out.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/udp.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/udp_checksum_gen.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/udp_complete.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/udp_ip_rx.v
  /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/imports/rtl/udp_ip_tx.v
}
read_vhdl -library xil_defaultlib /home/benjamin/Repositories/PynqNet/IpRepository/EtherNetComponent/EtherNetComponent.srcs/sources_1/new/EtherNetTopLevel.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top EtherNetTopLevel -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef EtherNetTopLevel.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file EtherNetTopLevel_utilization_synth.rpt -pb EtherNetTopLevel_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
