# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/PynqNetTop/PynqNetTop.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PynqNetTop || ORIG_REF_NAME==PynqNetTop} -quiet] -quiet

# IP: bd/PynqNetTop/ip/PynqNetTop_processing_system7_0_0/PynqNetTop_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PynqNetTop_processing_system7_0_0 || ORIG_REF_NAME==PynqNetTop_processing_system7_0_0} -quiet] -quiet

# IP: bd/PynqNetTop/ip/PynqNetTop_axi_gpio_0_0/PynqNetTop_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PynqNetTop_axi_gpio_0_0 || ORIG_REF_NAME==PynqNetTop_axi_gpio_0_0} -quiet] -quiet

# IP: bd/PynqNetTop/ip/PynqNetTop_auto_pc_0/PynqNetTop_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PynqNetTop_auto_pc_0 || ORIG_REF_NAME==PynqNetTop_auto_pc_0} -quiet] -quiet

# IP: bd/PynqNetTop/ip/PynqNetTop_ps7_0_axi_periph_0/PynqNetTop_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PynqNetTop_ps7_0_axi_periph_0 || ORIG_REF_NAME==PynqNetTop_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/PynqNetTop/ip/PynqNetTop_rst_ps7_0_100M_0/PynqNetTop_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PynqNetTop_rst_ps7_0_100M_0 || ORIG_REF_NAME==PynqNetTop_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/PynqNetTop/PynqNetTop_ooc.xdc
