# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ZyboENet/ZyboENet.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZyboENet || ORIG_REF_NAME==ZyboENet} -quiet] -quiet

# IP: bd/ZyboENet/ip/ZyboENet_processing_system7_0_0/ZyboENet_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZyboENet_processing_system7_0_0 || ORIG_REF_NAME==ZyboENet_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZyboENet/ip/ZyboENet_axi_gpio_0_0/ZyboENet_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZyboENet_axi_gpio_0_0 || ORIG_REF_NAME==ZyboENet_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ZyboENet/ip/ZyboENet_xbar_0/ZyboENet_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZyboENet_xbar_0 || ORIG_REF_NAME==ZyboENet_xbar_0} -quiet] -quiet

# IP: bd/ZyboENet/ip/ZyboENet_auto_pc_0/ZyboENet_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZyboENet_auto_pc_0 || ORIG_REF_NAME==ZyboENet_auto_pc_0} -quiet] -quiet

# IP: bd/ZyboENet/ip/ZyboENet_ps7_0_axi_periph_0/ZyboENet_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZyboENet_ps7_0_axi_periph_0 || ORIG_REF_NAME==ZyboENet_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ZyboENet/ip/ZyboENet_rst_ps7_0_100M_0/ZyboENet_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZyboENet_rst_ps7_0_100M_0 || ORIG_REF_NAME==ZyboENet_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ZyboENet/ip/ZyboENet_axi_gpio_1_0/ZyboENet_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZyboENet_axi_gpio_1_0 || ORIG_REF_NAME==ZyboENet_axi_gpio_1_0} -quiet] -quiet

# XDC: bd/ZyboENet/ZyboENet_ooc.xdc
